src/CMakeLists.txt: fix static build with mbedtls and zlib
Static build with a zlib-enabled mbedtls fails on:

[100%] Linking C executable rtty
/home/buildroot/autobuild/instance-2/output-1/host/opt/ext-toolchain/bin/../lib/gcc/microblazeel-buildroot-linux-uclibc/8.3.0/../../../../microblazeel-buildroot-linux-uclibc/bin/ld:
/home/buildroot/autobuild/instance-2/output-1/host/microblazeel-buildroot-linux-uclibc/sysroot/usr/lib/libmbedtls.a(ssl_tls.c.o):
in function `mbedtls_ssl_transform_free.part.24':
(.text+0x1724): undefined reference to `deflateEnd'

As mbedtls does not provide a pkg-config file, search for zlib and link
with it if necessary

Fixes:
 - http://autobuild.buildroot.org/results/61de143cdde1f0a9e734f46e9c68ce3504989890

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>